language: go

git:
  depth: 3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3
  - go get google.golang.org/grpc

before_script:
  - sudo apt-get install python3-setuptools
  - sudo easy_install3 pip
  - pip3 install requests

install:
  - go get github.com/clownpriest/trinity/core
  - go get github.com/clownpriest/trinity/core/system
  - go get github.com/clownpriest/trinity/core/config

script: python3 build.py install
