language: go

git:
  depth: 3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3
  - go get google.golang.org/grpc
  - go get github.com/clownpriest/trinity/core

before_script:
  - pip3 install requests

script: python3 build.py install
