language: go

sudo: required
dist: trusty

git:
  depth: 3

before_install:
  - sudo apt-get update -qq
  - go get google.golang.org/grpc
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 list

# before_script:
#   -

install:
  - go get github.com/clownpriest/trinity/core
  - go get github.com/clownpriest/trinity/core/system
  - go get github.com/clownpriest/trinity/core/config

script: python3 build.py travis
