language: go

sudo: required
dist: trusty

git:
  depth: 3

cache:
  directories:
  - $HOME/travis/gopath

before_install:
  - sudo apt-get update -qq
  - go get google.golang.org/grpc

install:
  - go get github.com/DataDog/zstd
  - go get github.com/ipfs/go-datastore
  - go get github.com/clownpriest/trinity/core
  - go get github.com/clownpriest/trinity/core/system
  - go get github.com/clownpriest/trinity/core/config

script: python3 build.py travis
